# Generated by Django 2.2.28 on 2025-03-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
