# Generated by Django 2.2.28 on 2025-03-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0002_cafe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to=settings.AUTH_USER_MODEL),
        ),
    ]
