# Generated by Django 2.2.28 on 2025-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0003_auto_20250326_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='ratings_no',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='ratings_total',
        ),
        migrations.AddField(
            model_name='cafe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_photos/'),
        ),
    ]
