# Generated by Django 2.2.28 on 2025-03-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0003_auto_20250326_1532'),
    ]

    operations = [
    ]
