# Generated by Django 2.2.28 on 2025-03-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0006_auto_20250327_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='rating_count',
            new_name='vote_count',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='rating_avg',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='rating_sum',
        ),
    ]
