# Generated by Django 2.2.28 on 2025-03-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0007_auto_20250327_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='vote_count',
        ),
    ]
