# Generated by Django 2.2.28 on 2025-03-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0004_auto_20250327_1333'),
        ('cafeCritics', '0008_remove_drink_vote_count'),
    ]

    operations = [
    ]
