# Generated by Django 2.2.28 on 2025-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0008_remove_drink_vote_count'),
        ('cafeCritics', '0009_merge_20250327_1636'),
    ]

    operations = [
    ]
