# Generated by Django 2.2.28 on 2025-03-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', 'fix_drink_model'),
        ('cafeCritics', '0010_merge_20250327_1822'),
    ]

    operations = [
    ]
