# Generated by Django 2.2.28 on 2025-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeCritics', '0011_merge_20250327_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_photos/'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
